### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by ephaee** [caseyscarborough/github-activity#15]
```
npm install
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 14.1.0
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Invalid name: "GitHub Activity Stream"
```

The name property in package.json can not contain uppercase letters or white spaces https://docs.npmjs.com/files/package.json#name

**Comment by caseyscarborough** [comment]
Thanks for pointing this out. I'd like to mention that this project should not use `npm install`, rather the script should be built with the `grunt` command.
