### ISSUE TITLE
'dist' folder contains all releases

### ISSUE THREAD

**Issue by raboof** [caseyscarborough/github-activity#20]

**Comment by caseyscarborough** [comment]
Would it be better to remove all but the most recent release?

**Comment by raboof** [comment]
That would make sense to me.

You could even argue the 'dist' folder should not be checked into version control, but then the question is how *do* we make those easily available to users.

**Comment by MasterRoot24** [comment]
The compiled code that's in `dist/` for each release should be added to the release that's created. I completely agree that they should not be committed to VCS.

See point 8 on the following link: https://help.github.com/articles/creating-releases/ and another mention of it on the GitHub blog here: https://github.com/blog/1547-release-your-software.

**Comment by caseyscarborough** [comment]
Thanks for the information @MasterRoot24. I will remove these and add them to the individual releases.
