### ISSUE TITLE
github-acitivity does on work using GitHub repository webhosting directly

### ISSUE THREAD

**Issue by philippschw** [caseyscarborough/github-activity#28]
Hello community, 

I am quite a newbie, therefore I ask for your patience. I am trying to publish my personal website, hosted by github and integrating the GitHub Activity Stream Widget. The widget works well, when I open the index.html as local file in my browser. However, the widget is missing (not even an error) when I push the files to github and use the GitHub repository webhosting directly and then open it as website. Do you have any suggestions why it does not work and what I can do about it?
Html files etc are available here:  https://github.com/philippschw/philippschw.github.io
Personal Website: https://philippschw.github.io/ 

Edit: Note, I run into the same issue using heroku webhosting.

**Comment by caseyscarborough** [comment]
Hi Philipp, it's showing on your site for me. Were you able to resolve the issue?

<img width="1122" alt="screen shot 2017-03-08 at 6 31 27 pm" src="https://cloud.githubusercontent.com/assets/3237612/23728958/7b3d27b0-042d-11e7-8a11-43ddc4988aa3.png">

**Comment by philippschw** [comment]
Hi Casey, thank you for your response. Yes I was able to fix it: replace every http with https and it works. Both heroku and github seem to enforce secure communication.  But your instruction works also I just did not read it well enough:

**It is either:** 
```
<link rel="stylesheet" href="https//cdnjs.cloudflare.com/ajax/libs/octicons/2.0.2/octicons.min.css">
<link rel="stylesheet" href="github-activity-0.1.4.min.css">

<script type="text/javascript" src="https//cdnjs.cloudflare.com/ajax/libs/mustache.js/0.7.2/mustache.min.js"></script>
<script type="text/javascript" src="github-activity-0.1.4.min.js"></script>
```
**or (as described in your Readme)** 
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/octicons/2.0.2/octicons.min.css">
<link rel="stylesheet" href="github-activity-0.1.4.min.css">

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/mustache.js/0.7.2/mustache.min.js"></script>
<script type="text/javascript" src="github-activity-0.1.4.min.js"></script>
```
**but not!!!**
```
<link rel="stylesheet" href="http//cdnjs.cloudflare.com/ajax/libs/octicons/2.0.2/octicons.min.css">
<link rel="stylesheet" href="github-activity-0.1.4.min.css">

<script type="text/javascript" src="http//cdnjs.cloudflare.com/ajax/libs/mustache.js/0.7.2/mustache.min.js"></script>
<script type="text/javascript" src="github-activity-0.1.4.min.js"></script>
```

**Comment by stopspazzing** [comment]
Just a heads up this was resolved and can be close :)
