### ISSUE TITLE
Can't find variable GithubActivity

### ISSUE THREAD

**Issue by SrujithPoondla** [caseyscarborough/github-activity#30]
I am newbie to JS, I followed instructions in the readme file. But i wasn't able to get the activity feed. I attached my html file in which i also included javascript just for testing.
[index.html.zip](https://github.com/caseyscarborough/github-activity/files/1175595/index.html.zip)

Thanks :)

**Comment by Darksmurf** [comment]
You reference many files that are not in the file system (at least, they aren't in the file system that you provided).
