### ISSUE TITLE
PR link is rendered incorrectly for review comments

### ISSUE THREAD

**Issue by nikhita** [caseyscarborough/github-activity#31]
A comment is shown as `nikhita commented on pull request kubernetes/kubernetes#47263`.

- For general comments in PRs (like https://github.com/kubernetes/kubernetes/pull/47263#issuecomment-321797634), `kubernetes/kubernetes#47263` links correctly to https://github.com/kubernetes/kubernetes/pull/47263.

- For review comments in PRs (like https://github.com/kubernetes/kubernetes/pull/47263#issuecomment-321797634), `kubernetes/kubernetes#47263` links incorrectly to `https://github.com/https://api.github.com/repos/kubernetes/kubernetes/pulls/47263`.

**Comment by caseyscarborough** [comment]
Thanks for reporting this! It's fixed now and I've released a new version released with the fix.

**Comment by nikhita** [comment]
@caseyscarborough Thanks for the quick fix! Also, thank you for such an awesome plugin! :)
